// flow-typed signature: 0138de87b594fefd499d4cd73a6a9577
// flow-typed version: <<STUB>>/postcss-gradient-transparency-fix_v^3.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-gradient-transparency-fix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-gradient-transparency-fix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-gradient-transparency-fix/index' {
  declare module.exports: $Exports<'postcss-gradient-transparency-fix'>;
}
declare module 'postcss-gradient-transparency-fix/index.js' {
  declare module.exports: $Exports<'postcss-gradient-transparency-fix'>;
}
